FROM openjdk:17-alpine

ARG JAR_FILE=target/TurkeyInfoBot.jar
ARG LAUNCH_FILE=launch.sh

ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG WEATHER_API_KEY
ARG WATER_TEMPERATURE_API_KEY
ARG BOT_TOKEN

WORKDIR /home/bot
COPY ${JAR_FILE} bot.jar
COPY ${LAUNCH_FILE} ${LAUNCH_FILE}

ENTRYPOINT ["launch.sh"]