#!/bin/sh -uex
java -D SPRING_DATASOURCE_URL="${SPRING_DATASOURCE_URL}" \
-D SPRING_DATASOURCE_USERNAME="${SPRING_DATASOURCE_USERNAME}" \
-D SPRING_DATASOURCE_PASSWORD="${SPRING_DATASOURCE_PASSWORD}" \
-D WEATHER_API_KEY="${WEATHER_API_KEY}" \
-D WATER_TEMPERATURE_API_KEY="${WATER_TEMPERATURE_API_KEY}" \
-D BOT_TOKEN="${BOT_TOKEN}" \
-jar bot.jar