name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Trigger Shell script
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote SSH commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: bash ${{ secrets.PATH_TO_SCRIPT }}
