name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - shell: bash
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.KEY }}
          SSH_HOST: ${{ secrets.HOST }}
          TEST: ${{ secrets.TEST }}
        run: |
          echo "$SSH_USER"
          echo "$SSH_KEY"
          echo "$SSH_HOST"
          echo "$TEST"
